all:
	cd projektProjektu ; make all
	cp projektProjektu/projekt.pdf .
	cd "dokumentacja uzytkownika" ; make all
	cp "dokumentacja uzytkownika/user-doc.pdf" .
	cp "protokol SW/ProjektSieci2.odt" protokoły.odt
	cd server ; make all
	cp server/server-działanie.pdf .
	cd pydoc ; make all

.PHONY:all
